SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP ;

SELECT EMPNO, ENAME, JOB, MGR,TO_CHAR (HIREDATE, 'MM/DD/YY HH24:MI:SS') , SAL, COMM, DEPTNO FROM EMP ;
--TO_CHAR(sysdate, 'MM/DD/YY HH24:MI:SS')


INSERT
INTO EMP
  (
    EMPNO, ENAME,JOB, MGR, HIREDATE, SAL, COMM,  DEPTNO)
  VALUES
  (
    80,
    'toto',
    'CLERK',
    7698,
    TO_DATE('27/02/2017 15:45:07', 'DD/MM/YYYY HH24:MI:SS'),
    1500.67,
    null,
    30
  );
  SELECT EMPNO, ENAME, JOB, MGR,TO_CHAR (HIREDATE, 'DD/MM/YYYY HH24:MI:SS') , SAL, COMM, DEPTNO
  FROM EMP where ename='toto';

  